### ISSUE TITLE
Proposal: Preserve original image

### ISSUE THREAD

**Issue by Yukaii** [cornguo/nKemono#2]
To make nKemono extension fit more for my daily workflow, I've implemented a prototype on [`preserve-original-image`](https://github.com/Yukaii/nKemono/tree/preserve-original-image) branch in my fork. I wrap each image with a new parent div, and set original image size to 1/3.

Here's a demo:

![kemono-inject-hover-zoom](https://cloud.githubusercontent.com/assets/4230968/25301037/ad4a4b08-274f-11e7-8492-fc613c75fb30.gif)

Original image stick to top-left of wrapper div.

However adding new div triggers `MutationObserver` every time and cause infinite loop. To workaround, I changed `runObserver` function: disconnect observer when replaceImages loop is over, then start observer again. (see ed8bad1 for detail)

If you are interested in current progress, we may have some discussion here and I can submit a new PR 😆

**Comment by cornguo** [comment]
That's awesome! :D

But I think thumbnail approach is too complex while I'd like to keep it simple. How about simply showing original image while mouse hovering over it?

**Comment by Yukaii** [comment]
@cornguo Thanks for the quick response 😄  Here's the new demo:

![kemono-inject-hover-switch](https://cloud.githubusercontent.com/assets/4230968/25301427/7e4cba0c-2759-11e7-9205-24bedcf041c6.gif)

**Comment by cornguo** [comment]
Cool!  Let's put it into new version. :D
